CREATE TABLE orders (
    id BIGSERIAL PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    payment_status VARCHAR(50) NOT NULL,
    shipment_status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES users (id)
);

-- Insert a deterministic seed user for our mock orders.
INSERT INTO users (id, name, email, password_hash, role, created_at, updated_at) 
VALUES (9999, 'Seed Customer', 'seed_customer@opspilot.com', 'dummy_hash', 'CUSTOMER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;

-- Seed 15 deterministic fake orders
INSERT INTO orders (id, customer_id, status, payment_status, shipment_status, created_at, updated_at) VALUES
(1001, 9999, 'DELIVERED', 'PAID', 'DELIVERED', CURRENT_TIMESTAMP - INTERVAL '10 days', CURRENT_TIMESTAMP - INTERVAL '8 days'),
(1002, 9999, 'SHIPPED', 'PAID', 'IN_TRANSIT', CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP - INTERVAL '1 days'),
(1003, 9999, 'PROCESSING', 'PAID', 'NOT_SHIPPED', CURRENT_TIMESTAMP - INTERVAL '1 hours', CURRENT_TIMESTAMP - INTERVAL '1 hours'),
(1004, 9999, 'PROCESSING', 'PENDING', 'NOT_SHIPPED', CURRENT_TIMESTAMP - INTERVAL '2 hours', CURRENT_TIMESTAMP - INTERVAL '2 hours'),
(1005, 9999, 'CANCELLED', 'REFUNDED', 'NOT_SHIPPED', CURRENT_TIMESTAMP - INTERVAL '5 days', CURRENT_TIMESTAMP - INTERVAL '4 days'),
(1006, 9999, 'DELIVERED', 'PAID', 'DELIVERED', CURRENT_TIMESTAMP - INTERVAL '20 days', CURRENT_TIMESTAMP - INTERVAL '15 days'),
(1007, 9999, 'SHIPPED', 'PAID', 'IN_TRANSIT', CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP - INTERVAL '1 days'),
(1008, 9999, 'PROCESSING', 'PAID', 'NOT_SHIPPED', CURRENT_TIMESTAMP - INTERVAL '4 hours', CURRENT_TIMESTAMP - INTERVAL '3 hours'),
(1009, 9999, 'PROCESSING', 'FAILED', 'NOT_SHIPPED', CURRENT_TIMESTAMP - INTERVAL '1 days', CURRENT_TIMESTAMP - INTERVAL '1 days'),
(1010, 9999, 'CANCELLED', 'REFUNDED', 'NOT_SHIPPED', CURRENT_TIMESTAMP - INTERVAL '8 days', CURRENT_TIMESTAMP - INTERVAL '7 days'),
(1011, 9999, 'DELIVERED', 'PAID', 'DELIVERED', CURRENT_TIMESTAMP - INTERVAL '30 days', CURRENT_TIMESTAMP - INTERVAL '25 days'),
(1012, 9999, 'SHIPPED', 'PAID', 'IN_TRANSIT', CURRENT_TIMESTAMP - INTERVAL '4 days', CURRENT_TIMESTAMP - INTERVAL '2 days'),
(1013, 9999, 'PROCESSING', 'PAID', 'NOT_SHIPPED', CURRENT_TIMESTAMP - INTERVAL '5 hours', CURRENT_TIMESTAMP - INTERVAL '4 hours'),
(1014, 9999, 'PROCESSING', 'PENDING', 'NOT_SHIPPED', CURRENT_TIMESTAMP - INTERVAL '6 hours', CURRENT_TIMESTAMP - INTERVAL '5 hours'),
(1015, 9999, 'CANCELLED', 'REFUNDED', 'NOT_SHIPPED', CURRENT_TIMESTAMP - INTERVAL '12 days', CURRENT_TIMESTAMP - INTERVAL '11 days');
