package com.opspilot.audit.domain.model;
public enum AuditAction {
    LOGIN,
    TICKET_CREATED,
    TICKET_ASSIGNED,
    TICKET_STATUS_CHANGED,
    TICKET_NOTE_ADDED,
    ORDER_CANCELLATION_REQUESTED,
    ORDER_CANCELLATION_EXECUTED,
    ORDER_CANCELLATION_REJECTED,
    AI_REQUESTED_ACTION,
    SYSTEM_EXECUTED_ACTION
}